### ISSUE TITLE
Bug: Missing `.d.ts` files for some icons

### ISSUE THREAD

**Issue by vigenere23** [ramiroaisen/svelte-material-icons#11]
Some icons, like `Settings`, do not have a generated `.d.ts` file, which results in a `Could not find a declaration file for module 'svelte-material-icons/Settings.svelte'. '/home/something.svelte' implicitly has an 'any' type.ts(7016)` error.

Expected: There is a single `.d.ts` file generated for every icon.

**Comment by ramiroaisen** [comment]
Thanks for pointing this out, it's fixed in latest version at npm.
