### ISSUE TITLE
Unmet peer dependency - Svelte version 4.0.0

### ISSUE THREAD

**Issue by Sigvel** [ramiroaisen/svelte-material-icons#17]
Warning: svelte-material-icons package requires a peer dependency of svelte version ^3.0.0, when using version 4.0.0 of svelte.

Updating the svelte peerDependencies field in your package.json file should solve this issue. If there isnt other breaking changes you need to take account for.

**Comment by ramiroaisen** [comment]
Merged and published to npm as version 3.0.5
